<?php

namespace AppBundle\Repository;

/**
 * ActividadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActividadRepository extends \Doctrine\ORM\EntityRepository
{
	public function searchByName($q, $id_user) {
		$entityManager = $this->getEntityManager();
		$query = $entityManager->createQuery(
            'SELECT a
            FROM AppBundle:Actividad a
            WHERE a.nombre LIKE :q AND
            a.usuario = :id_user
            ORDER BY a.estado ASC'
        )->setParameters(array('q' => '%'.$q.'%', 'id_user' => $id_user));
        return $query->getResult();
	}
}
