<?php

namespace AppBundle\Repository;

/**
 * ActividadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActividadRepository extends \Doctrine\ORM\EntityRepository
{
	public function searchByName($q) {
		$entityManager = $this->getEntityManager();
		$query = $entityManager->createQuery(
            'SELECT a
            FROM AppBundle:Actividad a
            WHERE a.nombre LIKE :q
            ORDER BY a.estado ASC'
        )->setParameter('q', '%'.$q.'%');
        return $query->getResult();
	}
}
