<?php

namespace AppBundle\Repository;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends \Doctrine\ORM\EntityRepository
{

	public function all_category_tasks($id_user) {
		$entityManager = $this->getEntityManager();
		$query = $entityManager->createQuery(
            'SELECT c, a
            FROM AppBundle:Categoria c 
            JOIN c.actividades a
            WHERE a.usuario = :id_user
            ORDER BY a.estado ASC'
        )->setParameter('id_user', $id_user);
        return $query->getResult();
	}

    public function search_category_tasks($q, $id_user) {
        $entityManager = $this->getEntityManager();
        $query = $entityManager->createQuery(
            'SELECT c, a
            FROM AppBundle:Categoria c 
            JOIN c.actividades a
            WHERE a.nombre LIKE :q AND
            a.usuario = :id_user
            ORDER BY a.estado ASC'
        )->setParameters(array('q' => '%'.$q.'%', 'id_user' => $id_user));
        return $query->getResult();
    }
}
