<?php

namespace AppBundle\Repository;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends \Doctrine\ORM\EntityRepository
{

	public function all_category_tasks() {
		$entityManager = $this->getEntityManager();
		$query = $entityManager->createQuery(
            'SELECT c, a
            FROM AppBundle:Categoria c 
            JOIN c.actividades a
            ORDER BY a.estado ASC'
        );
        return $query->getResult();
	}

    public function search_category_tasks($q) {
        $entityManager = $this->getEntityManager();
        $query = $entityManager->createQuery(
            'SELECT c, a
            FROM AppBundle:Categoria c 
            JOIN c.actividades a
            WHERE a.nombre LIKE :q
            ORDER BY a.estado ASC'
        )->setParameter('q', '%'.$q.'%');
        return $query->getResult();
    }
}
